name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    container:
      image: ascendai/python:3.9-ubuntu20.04
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[build]

      - name: Build binary
        run: ./build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/whistle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
